// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shelter.Models;

namespace Shelter.Migrations
{
    [DbContext(typeof(ShelterContext))]
    [Migration("20210123235158_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shelter.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 6,
                            Breed = "American Shorthair",
                            Name = "Alphred",
                            Sex = "Female"
                        },
                        new
                        {
                            Id = 2,
                            Age = 7,
                            Breed = "Bombay",
                            Name = "Unfried",
                            Sex = "Male"
                        },
                        new
                        {
                            Id = 3,
                            Age = 8,
                            Breed = "Cyprus",
                            Name = "Hans",
                            Sex = "Female"
                        },
                        new
                        {
                            Id = 4,
                            Age = 9,
                            Breed = "Devon Rex",
                            Name = "Gilbert",
                            Sex = "Male"
                        },
                        new
                        {
                            Id = 5,
                            Age = 10,
                            Breed = "Egyptian Mau",
                            Name = "Heathrow",
                            Sex = "Female"
                        });
                });

            modelBuilder.Entity("Shelter.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 6,
                            Breed = "Akita",
                            Name = "Higgins",
                            Sex = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Age = 7,
                            Breed = "Belgian Shepherd",
                            Name = "Basil",
                            Sex = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Age = 8,
                            Breed = "Chilean Terrier",
                            Name = "Oliver",
                            Sex = "Male"
                        },
                        new
                        {
                            Id = 4,
                            Age = 9,
                            Breed = "Dingo",
                            Name = "Hammond",
                            Sex = "Female"
                        },
                        new
                        {
                            Id = 5,
                            Age = 10,
                            Breed = "Estonian Hound",
                            Name = "Sigfried",
                            Sex = "Male"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
