// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shelter.Models;

namespace Shelter.Migrations
{
    [DbContext(typeof(ShelterContext))]
    [Migration("20210123213754_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CatAge");

                    b.Property<string>("CatBreed")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("CatSex")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            CatAge = 6,
                            CatBreed = "American Shorthair",
                            CatName = "Alphred",
                            CatSex = "Female"
                        },
                        new
                        {
                            CatId = 2,
                            CatAge = 7,
                            CatBreed = "Bombay",
                            CatName = "Unfried",
                            CatSex = "Male"
                        },
                        new
                        {
                            CatId = 3,
                            CatAge = 8,
                            CatBreed = "Cyprus",
                            CatName = "Hans",
                            CatSex = "Female"
                        },
                        new
                        {
                            CatId = 4,
                            CatAge = 9,
                            CatBreed = "Devon Rex",
                            CatName = "Gilbert",
                            CatSex = "Male"
                        },
                        new
                        {
                            CatId = 5,
                            CatAge = 10,
                            CatBreed = "Egyptian Mau",
                            CatName = "Heathrow",
                            CatSex = "Female"
                        });
                });

            modelBuilder.Entity("Shelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DogAge");

                    b.Property<string>("DogBreed")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("DogName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("DogSex")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            DogAge = 6,
                            DogBreed = "Akita",
                            DogName = "Higgins",
                            DogSex = "Male"
                        },
                        new
                        {
                            DogId = 2,
                            DogAge = 7,
                            DogBreed = "Belgian Shepherd",
                            DogName = "Basil",
                            DogSex = "Female"
                        },
                        new
                        {
                            DogId = 3,
                            DogAge = 8,
                            DogBreed = "Chilean Terrier",
                            DogName = "Oliver",
                            DogSex = "Male"
                        },
                        new
                        {
                            DogId = 4,
                            DogAge = 9,
                            DogBreed = "Dingo",
                            DogName = "Hammond",
                            DogSex = "Female"
                        },
                        new
                        {
                            DogId = 5,
                            DogAge = 10,
                            DogBreed = "Estonian Hound",
                            DogName = "Sigfried",
                            DogSex = "Male"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
